### ISSUE TITLE
YT playlist import playback issue 

### ISSUE THREAD

**Issue by TydoTydo** [23rd/PotPlayerExtentions#10]
Recently I've been trying to watch a few YT playlists on Potplayer which in particular are over a year old. And I'm getting a "failed to start playback" error on trying to load the individual videos after the playlist successfully imports. 

Steps:
1. Import YT playlist via "Open URL..." in Potplayer
(https://www.youtube.com/playlist?list=PLxYb6LVQvyFYqDWPMoU1qGzBV9CM2QN-P)
2. Try to play any of the files in the playlist

Result:
On 1st play attempt the file results in "failed to start playback"
On 2nd play attempt the file loads 90% of the time and 10% of the time I get the same error
On 3rd attempt the file loads 100% of the time.

Sometimes the Error does not does not occur on the very first playback attempt after URL playlist import. And if first playback works then immediate playback of other files will work. To get the error to popup in this case you have to watch a portion of the video first

Alternative Steps: 
1. Import YT playlist via "Open URL..." in Potplayer
(https://www.youtube.com/playlist?list=PLxYb6LVQvyFYqDWPMoU1qGzBV9CM2QN-P)
2. Try to play any of the files in the playlist
3. Watch most of the video (I'm using "most" to exclude any possibilities of any issues with reaching the end of the file. so just get near to the end of the file)
4. Try to load next file. 

Result (Same):
On 1st play attempt the file (of step 4) results in "failed to start playback"
On 2nd play attempt the file (of step 4) loads 90% of the time and 10% of the time I get the same error
On 3rd attempt the file (of step 4) loads 100% of the time.

If the Error does not result from first set of steps it results from the 2nd set of steps 100% of the time for me for multiple older YT imported playlists.
 
Notes:
Only seems to happen on older playlists I've tried to play
Newer playlists I've tried recently don't have the issue
Sorry If any of that was confusing I tried to be as clear as I could.

**Comment by 23rd** [comment]
Did you install Goodgame extension or only Twitch?

**Comment by TydoTydo** [comment]
Only Twitch

**Comment by TydoTydo** [comment]
And I guess this is the wrong place to post. For some reason I thought your extension covered Twitch and YouTube. But I see It only affects Twitch

**Comment by 23rd** [comment]
Yes. YouTube extention is build in feature.
